### ISSUE TITLE
Investigate and fix Python/flake8 issue

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-api#1103]
**NOTE:** This is currently affecting both the API and Admin repos and will need to be addressed in each of them.

Our pull requests are now starting to fail their checks because of an issue that appears to be happening between `flake8` and Python.  This stack trace appears in our `build` task:

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/notifications-api-b9iyFBae-py3.12/lib/python3.12/site-packages/flake8/checker.py", line 83, in _mp_run
    ).run_checks()
      ^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/notifications-api-b9iyFBae-py3.12/lib/python3.12/site-packages/flake8/checker.py", line 527, in run_checks
    self.process_tokens()
  File "/home/runner/.cache/pypoetry/virtualenvs/notifications-api-b9iyFBae-py3.12/lib/python3.12/site-packages/flake8/checker.py", line 512, in process_tokens
    self.handle_newline(token_type)
  File "/home/runner/.cache/pypoetry/virtualenvs/notifications-api-b9iyFBae-py3.12/lib/python3.12/site-packages/flake8/checker.py", line 542, in handle_newline
    self.run_logical_checks()
  File "/home/runner/.cache/pypoetry/virtualenvs/notifications-api-b9iyFBae-py3.12/lib/python3.12/site-packages/flake8/checker.py", line 439, in run_logical_checks
    comments, logical_line, mapping = self.processor.build_logical_line()
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/notifications-api-b9iyFBae-py3.12/lib/python3.12/site-packages/flake8/processor.py", line 231, in build_logical_line
    comments, logical, mapping_list = self.build_logical_line_tokens()
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/notifications-api-b9iyFBae-py3.12/lib/python3.12/site-packages/flake8/processor.py", line 212, in build_logical_line_tokens
    previous_text = self.lines[row_index][column_index]
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
IndexError: string index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/notifications-api-b9iyFBae-py3.12/bin/flake8", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/notifications-api-b9iyFBae-py3.12/lib/python3.12/site-packages/flake8/main/cli.py", line 23, in main
    app.run(argv)
  File "/home/runner/.cache/pypoetry/virtualenvs/notifications-api-b9iyFBae-py3.12/lib/python3.12/site-packages/flake8/main/application.py", line 198, in run
    self._run(argv)
  File "/home/runner/.cache/pypoetry/virtualenvs/notifications-api-b9iyFBae-py3.12/lib/python3.12/site-packages/flake8/main/application.py", line 187, in _run
    self.run_checks()
  File "/home/runner/.cache/pypoetry/virtualenvs/notifications-api-b9iyFBae-py3.12/lib/python3.12/site-packages/flake8/main/application.py", line 103, in run_checks
    self.file_checker_manager.run()
  File "/home/runner/.cache/pypoetry/virtualenvs/notifications-api-b9iyFBae-py3.12/lib/python3.12/site-packages/flake8/checker.py", line 236, in run
    self.run_parallel()
  File "/home/runner/.cache/pypoetry/virtualenvs/notifications-api-b9iyFBae-py3.12/lib/python3.12/site-packages/flake8/checker.py", line [20](https://github.com/GSA/notifications-api/actions/runs/9587533926/job/26437769268?pr=1101#step:6:21)5, in run_parallel
    self.results = list(pool.imap_unordered(_mp_run, self.filenames))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/multiprocessing/pool.py", line 873, in next
    raise value
IndexError: string index out of range
Error: Process completed with exit code 1.
```

At a glance, it _appears_ that GitHub is now using a newer version of Python, `3.12.4`, where as at least some of us locally are still on `3.12.2`.  The [Dependabot PR to update `flake8`](https://github.com/GSA/notifications-api/pull/1092) is suffering from the same issue, unfortunately, so that doesn't appear to be the easy fix.

## Implementation Sketch and Acceptance Criteria

- [x] Investigate what is happening with the PR build failures and if possible, try and replicate locally.
   - With `pyenv` installed, you can easily install the newest 3.12 release of Python and create new virtual environments against it; use those with the projects and try running `flake8` and see if the same issue happens.
   - **NOTE:** You may need to update `pyenv` first so that you have the option to install Python 3.12.4.
- [x] Check to see if there's an even newer version of `flake8` that Dependabot hasn't caught yet and see if that fixes the issue.
- [x] Check to see if we need to pin the Python version to something like `3.12.3` instead of pulling the latest.
- [x] Fix the issue and make any adjustments necessary in our `checks` workflow, dependency updates, etc.

## Security Considerations

- We want to make sure that all of our checks continue to run and pass properly so that we are as well guarded against adverse changes as possible.
- While we want to be running the latest and greatest stable things, sometimes breaking changes are introduced and we cannot upgrade to the latest version; this might be a case where we have to pin something to a slightly older release until the issue is fixed.

**Comment by ccostino** [comment]
Welp, looks like we need to target `3.12.3` instead`. In addition to the files that Ken modified previously, we also need to adjust the `runtime.txt` file at the root of both repos to reference `3.12.3`.

**Comment by ccostino** [comment]
We've resolved this issue in both the API and the Admin.  Thanks, @terrazoon!
