### ISSUE TITLE
Exception Investigation:  sqlalchemy.exc:NoResultFound

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-api#1134]
This is one of the errors we've seen captured in New Relic that we'd like to dig into and understand, if not also resolve.

**Error message:**
No row was found when one was required
Path: /service/XXXXXXX/job/XXXXXXX
Exception:  sqlalchemy.exc:NoResultFound

```
Traceback (most recent call last):
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/eventlet/greenthread.py", line 265, in main
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/gunicorn/workers/geventlet.py", line 157, in handle
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/gunicorn/workers/base_async.py", line 55, in handle
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/gunicorn/workers/base_async.py", line 108, in handle_request
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/newrelic/api/wsgi_application.py", line 669, in _nr_wsgi_application_wrapper_
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/flask/app.py", line 1498, in __call__
File "/home/vcap/app/notifications_utils/request_helper.py", line 80, in __call__
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/newrelic/api/wsgi_application.py", line 564, in _nr_wsgi_application_wrapper_
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/newrelic/hooks/framework_flask.py", line 79, in _nr_wrapper_handler_
File "/home/vcap/app/app/job/rest.py", line 46, in get_job_by_service_and_job_id
File "/home/vcap/app/app/dao/jobs_dao.py", line 45, in dao_get_job_by_service_id_and_job_id
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2778, in one
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/sqlalchemy/engine/result.py", line 1810, in one
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/sqlalchemy/engine/result.py", line 752, in _only_one_row
```

## Implementation Sketch and Acceptance Criteria

- [ ] Look through our log history at https://logs.fr.cloud.gov/ and see if any patterns emerge that might indicate what conditions cause this
- [ ] Try and replicate the error, if possible
- [ ] Follow up in this issue with any findings and possible remediation steps

## Security Considerations

- Be mindful of not sharing sensitive information.
- We'd like to reduce the errors that occur in the application where possible to maintain application stability and performance, and reduce the chances that the application ends up in an error or invalid state.

**Comment by terrazoon** [comment]
This is because the front end, after it creates a job, has to poll until the database is populated with that job.   There is a proposed solution to separate 'create_job' from 'start_job' so the front end would not have to poll and generate these errors, but it appears to be blocked.  See:  https://github.com/orgs/GSA/projects/20/views/1?filterQuery=shum&pane=issue&itemId=59355411

**Comment by ccostino** [comment]
Okay, sounds like this is already tracked with the issue and is a symptom of that.  I'll link to this to the other one, thanks @terrazoon!
