### ISSUE TITLE
Live customer issue exception investigation:  botocore.errorfactory:NoSuchKey

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-api#1169]
There is a live issue affecting at least one pilot partner's service, where if you try to go to the main service page (the dashboard) or look at all notifications, the API throws an exception.  When you visit this admin URL - `https://beta.notify.gov/services/<SERVICE_GUID>` - it results in an API request that hits this URL endpoint: `/services/<SERVICE_GUID>/notifications` - this is where the exception is occurring.

This seems to be only affecting the Washington State service pilot partner at the moment.

## Exception Details

**Error message:**  An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.

**Stack Trace:**

```
Traceback (most recent call last):
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/eventlet/greenthread.py", line 265, in main
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/gunicorn/workers/geventlet.py", line 157, in handle
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/gunicorn/workers/base_async.py", line 55, in handle
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/gunicorn/workers/base_async.py", line 108, in handle_request
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/newrelic/api/wsgi_application.py", line 669, in _nr_wsgi_application_wrapper_
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/flask/app.py", line 1498, in __call__
File "/home/vcap/app/notifications_utils/request_helper.py", line 80, in __call__
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/newrelic/api/wsgi_application.py", line 564, in _nr_wsgi_application_wrapper_
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/newrelic/hooks/framework_flask.py", line 79, in _nr_wrapper_handler_
File "/home/vcap/app/app/service/rest.py", line 447, in get_all_notifications_for_service
File "/home/vcap/app/app/aws/s3.py", line 192, in get_personalisation_from_s3
File "/home/vcap/app/app/aws/s3.py", line 78, in get_job_from_s3
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/boto3/resources/factory.py", line 581, in do_action
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/boto3/resources/action.py", line 88, in __call__
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/botocore/client.py", line 565, in _api_call
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/botocore/client.py", line 1021, in _make_api_call
```

## Implementation Sketch and Acceptance Criteria

- [ ] Investigate the cause of the error in the API and try to recreate the issue locally to understand what is happening
   - Reach out to @em-herrick for details if you need help investigating in production
- [ ] Make the appropriate fix(es) needed
- [ ] Update tests as necessary

## Security Considerations

- No major security considerations with this, it seems to be a case of either a key being referenced incorrectly and/or missing data that needs to be handled appropriately so the page still loads and the application functions correctly.

**Comment by em-herrick** [comment]
Partners view this page when clicking on dashboard

![image](https://github.com/GSA/notifications-api/assets/91496588/186ec182-cab8-4ddd-ad6f-ed66751b05ca)
