### ISSUE TITLE
Investigate builtins:BrokenPipeError when attempting to connect to S3

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-api#1393]
We're still seeing a handful of `builtins:BrokenPipeError` now, and it looks like it's all while trying to connect to S3 under specific conditions:

```
Traceback (most recent call last):
File "/home/vcap/deps/0/bin/celery", line 8, in <module>
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/__main__.py", line 15, in main
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/bin/celery.py", line 236, in main
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/click/core.py", line 1078, in main
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/click/core.py", line 783, in invoke
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/bin/base.py", line 135, in caller
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/bin/worker.py", line 356, in worker
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/worker/worker.py", line 202, in start
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/bootsteps.py", line 116, in start
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/bootsteps.py", line 365, in start
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/concurrency/base.py", line 130, in start
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/concurrency/prefork.py", line 109, in on_start
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/billiard/pool.py", line 1046, in __init__
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/billiard/pool.py", line 1158, in _create_worker_process
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/billiard/process.py", line 120, in start
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/billiard/context.py", line 331, in _Popen
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/billiard/popen_fork.py", line 22, in __init__
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/billiard/popen_fork.py", line 77, in _launch
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/billiard/process.py", line 323, in _bootstrap
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/billiard/process.py", line 110, in run
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/billiard/pool.py", line 292, in __call__
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/billiard/pool.py", line 362, in workloop
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/app/trace.py", line 651, in fast_trace_task
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task
File "/home/vcap/app/app/__init__.py", line 418, in __call__
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/newrelic/hooks/application_celery.py", line 123, in wrapper
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__
File "/home/vcap/app/app/celery/tasks.py", line 446, in regenerate_job_cache
File "/home/vcap/app/app/aws/s3.py", line 195, in get_s3_files
File "<string>", line 2, in __len__
File "/home/vcap/deps/0/python/lib/python3.12/multiprocessing/managers.py", line 820, in _callmethod
File "/home/vcap/deps/0/python/lib/python3.12/multiprocessing/connection.py", line 206, in send
File "/home/vcap/deps/0/python/lib/python3.12/multiprocessing/connection.py", line 427, in _send_bytes
File "/home/vcap/deps/0/python/lib/python3.12/multiprocessing/connection.py", line 384, in _send
```

Specifically, it's when trying to regenerate the job cache it looks like:

```
File "/home/vcap/app/app/celery/tasks.py", line 446, in regenerate_job_cache
File "/home/vcap/app/app/aws/s3.py", line 195, in get_s3_files
```

## Implementation Sketch and Acceptance Criteria

- [ ] Trace the code path starting at the point of the exception being thrown to how the job cache is first instantiated; see if there are any spots where a potential breakdown could occur when trying to connect to S3
   - Pay close attention to the S3 connectivity pieces in this process - are we hammering S3 and need to back off?  Is there retry logic implemented? 
   - What else could potentially be causing a connectivity issue?
- [ ] Based on findings, make any recommendations or adjustments as necessary

## Security Considerations

- We want to make sure our application is behaving and handling exceptions properly to prevent instability.

**Comment by ccostino** [comment]
Closing this issue now as it was fixed with the other adjustments we made earlier this week!  It was being caused by the either the shared cache being blown away and/or the Celery workers getting bogged down.
