### ISSUE TITLE
Investigate builtins:ValueError - not enough values to unpack (expected 3, got 2) - again

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-api#1467]
This error continues to show up despite our previous investigations and fixes around it, and we saw it crop up a fair amount with the larger batches we had run this week.

We need to get to the bottom of this for good and get some proper error handling in place for it and ideally fix the root cause(s) as well.

The full stack trace:

```Traceback (most recent call last):
File "/home/vcap/deps/0/bin/celery", line 8, in <module>
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/__main__.py", line 15, in main
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/bin/celery.py", line 236, in main
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/click/core.py", line 1078, in main
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/click/core.py", line 783, in invoke
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/bin/base.py", line 135, in caller
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/bin/worker.py", line 356, in worker
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/worker/worker.py", line 202, in start
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/bootsteps.py", line 116, in start
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/bootsteps.py", line 365, in start
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 340, in start
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/bootsteps.py", line 116, in start
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 746, in start
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/worker/loops.py", line 97, in asynloop
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/kombu/asynchronous/hub.py", line 308, in create_loop
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/kombu/asynchronous/hub.py", line 149, in fire_timers
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/kombu/asynchronous/timer.py", line 70, in __call__
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/kombu/asynchronous/timer.py", line 137, in _reschedules
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/billiard/pool.py", line 1351, in maintain_pool
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/billiard/pool.py", line 1343, in _maintain_pool
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/billiard/pool.py", line 1328, in _repopulate_pool
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/billiard/pool.py", line 1158, in _create_worker_process
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/billiard/process.py", line 120, in start
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/billiard/context.py", line 331, in _Popen
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/billiard/popen_fork.py", line 22, in __init__
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/billiard/popen_fork.py", line 77, in _launch
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/billiard/process.py", line 323, in _bootstrap
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/billiard/process.py", line 110, in run
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/billiard/pool.py", line 292, in __call__
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/billiard/pool.py", line 362, in workloop
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/app/trace.py", line 651, in fast_trace_task
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task
File "/home/vcap/app/app/__init__.py", line 422, in __call__
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/newrelic/hooks/application_celery.py", line 123, in wrapper
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__
File "/home/vcap/app/app/celery/provider_tasks.py", line 52, in check_sms_delivery_receipt```

The issue seems to lie with whatever `check_sms_delivery_receipt` is receiving; let's make sure whatever makes that call is doing it properly, and let's get some proper error handling and logging in `check_sms_delivery_receipt` itself so this doesn't continue to pollute our logs and New Relic.

**Comment by ccostino** [comment]
@terrazoon this stack trace and error may have been caught with some of the other recent updates, right?  If not, then this would be worth double checking to see if there's something still not right.
