### ISSUE TITLE
Phone number parsing  error on registration

### ISSUE THREAD

**Issue by samathad2023** [GSA/notifications-api#836]
## Description
Repro steps

- Login /sign in to notify admin (use phonenumber either with space or without 1 just the 10digits xxxxxxxxxx)
- Enter text message code (two factor sms)
- Create new service 
- Click on 'send  messages' button
- Select existing template or create a new template
- On Send 'notify' screen click button 'use my phonenumber'
- Preview of 'notify' screen select now option and click button 'send 1test message'

Expected Result 

- Sms message gets delivered

Actual Result

- No message gets delivered
- Error  as `09:42:00 worker.1    | [2024-03-06 09:42:00,011: INFO/ForkPoolWorker-4] Task check-job-status[1b874cdf-e11e-4b95-8ddb-e7cf62f6c3f9] succeeded in 0.00533841599826701s: None
09:42:13 worker.1    | 2024-03-06T09:42:13 delivery delivery ERROR no-request-id no-service-id "Celery task check_sms_delivery_receipt (queue: check-sms_tasks) failed" [in /Users/sdondeti/.pyenv/versions/3.12.2/envs/notify-api-upgrade/lib/python3.12/site-packages/notifications_utils/celery.py:48]
09:42:13 worker.1    | Traceback (most recent call last):
09:42:13 worker.1    |   File "/Users/sdondeti/.pyenv/versions/3.12.2/envs/notify-api-upgrade/lib/python3.12/site-packages/celery/app/trace.py", line 477, in trace_task
09:42:13 worker.1    |     R = retval = fun(*args, **kwargs)
09:42:13 worker.1    |                  ^^^^^^^^^^^^^^^^^^^^
09:42:13 worker.1    |   File "/Users/sdondeti/.pyenv/versions/3.12.2/envs/notify-api-upgrade/lib/python3.12/site-packages/notifications_utils/celery.py", line 59, in __call__
09:42:13 worker.1    |     return super().__call__(*args, **kwargs)
09:42:13 worker.1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
09:42:13 worker.1    |   File "/Users/sdondeti/.pyenv/versions/3.12.2/envs/notify-api-upgrade/lib/python3.12/site-packages/celery/app/trace.py", line 760, in __protected_call__
09:42:13 worker.1    |     return self.run(*args, **kwargs)
09:42:13 worker.1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
09:42:13 worker.1    |   File "/Users/sdondeti/Desktop/notifications-api/app/celery/provider_tasks.py", line 49, in check_sms_delivery_receipt
09:42:13 worker.1    |     status, provider_response, carrier = aws_cloudwatch_client.check_sms(
09:42:13 worker.1    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
09:42:13 worker.1    |   File "/Users/sdondeti/Desktop/notifications-api/app/clients/cloudwatch/aws_cloudwatch.py", line 118, in check_sms
09:42:13 worker.1    |     filter_pattern = filter_pattern.replace("XXXXX", message_id)
09:42:13 worker.1    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
09:42:13 worker.1    | TypeError: replace() argument 2 must be str, not None
09:42:13 worker.1    | [2024-03-06 09:42:13,244: ERROR/ForkPoolWorker-4] Celery task check_sms_delivery_receipt (queue: check-sms_tasks) failed
09:42:13 worker.1    | Traceback (most recent call last):
09:42:13 worker.1    |   File "/Users/sdondeti/.pyenv/versions/3.12.2/envs/notify-api-upgrade/lib/python3.12/site-packages/celery/app/trace.py", line 477, in trace_task
09:42:13 worker.1    |     R = retval = fun(*args, **kwargs)
09:42:13 worker.1    |                  ^^^^^^^^^^^^^^^^^^^^
09:42:13 worker.1    |   File "/Users/sdondeti/.pyenv/versions/3.12.2/envs/notify-api-upgrade/lib/python3.12/site-packages/notifications_utils/celery.py", line 59, in __call__
09:42:13 worker.1    |     return super().__call__(*args, **kwargs)
09:42:13 worker.1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
09:42:13 worker.1    |   File "/Users/sdondeti/.pyenv/versions/3.12.2/envs/notify-api-upgrade/lib/python3.12/site-packages/celery/app/trace.py", line 760, in __protected_call__
09:42:13 worker.1    |     return self.run(*args, **kwargs)
09:42:13 worker.1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
09:42:13 worker.1    |   File "/Users/sdondeti/Desktop/notifications-api/app/celery/provider_tasks.py", line 49, in check_sms_delivery_receipt
09:42:13 worker.1    |     status, provider_response, carrier = aws_cloudwatch_client.check_sms(
09:42:13 worker.1    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
09:42:13 worker.1    |   File "/Users/sdondeti/Desktop/notifications-api/app/clients/cloudwatch/aws_cloudwatch.py", line 118, in check_sms
09:42:13 worker.1    |     filter_pattern = filter_pattern.replace("XXXXX", message_id)
09:42:13 worker.1    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
09:42:13 worker.1    | TypeError: replace() argument 2 must be str, not None
09:42:13 worker.1    | [2024-03-06 09:42:13,245: ERROR/ForkPoolWorker-4] Task check_sms_delivery_receipt[c3b8872e-f2f9-46ac-a1e2-efd86ef96eb4] raised unexpected: TypeError('replace() argument 2 must be str, not None')
09:42:13 worker.1    | Traceback (most recent call last):
09:42:13 worker.1    |   File "/Users/sdondeti/.pyenv/versions/3.12.2/envs/notify-api-upgrade/lib/python3.12/site-packages/celery/app/trace.py", line 477, in trace_task
09:42:13 worker.1    |     R = retval = fun(*args, **kwargs)
09:42:13 worker.1    |                  ^^^^^^^^^^^^^^^^^^^^
09:42:13 worker.1    |   File "/Users/sdondeti/.pyenv/versions/3.12.2/envs/notify-api-upgrade/lib/python3.12/site-packages/notifications_utils/celery.py", line 59, in __call__
09:42:13 worker.1    |     return super().__call__(*args, **kwargs)
09:42:13 worker.1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
09:42:13 worker.1    |   File "/Users/sdondeti/.pyenv/versions/3.12.2/envs/notify-api-upgrade/lib/python3.12/site-packages/celery/app/trace.py", line 760, in __protected_call__
09:42:13 worker.1    |     return self.run(*args, **kwargs)
09:42:13 worker.1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
09:42:13 worker.1    |   File "/Users/sdondeti/Desktop/notifications-api/app/celery/provider_tasks.py", line 49, in check_sms_delivery_receipt
09:42:13 worker.1    |     status, provider_response, carrier = aws_cloudwatch_client.check_sms(
09:42:13 worker.1    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
09:42:13 worker.1    |   File "/Users/sdondeti/Desktop/notifications-api/app/clients/cloudwatch/aws_cloudwatch.py", line 118, in check_sms
09:42:13 worker.1    |     filter_pattern = filter_pattern.replace("XXXXX", message_id)
09:42:13 worker.1    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
09:42:13 worker.1    | TypeError: replace() argument 2 must be str, not None
09:43:00 scheduler.1 | [2024-03-06 09:43:00,000: INFO/MainProcess] Scheduler: Sending due task check-job-status (check-job-status)`

**Comment by samathad2023** [comment]
I have tried few times with different version and combination of 3.9 and 3.12 version for api and admin to repro the scenario. We initially though it was due to phone number with out 1 at the beginning. The issue was fixed for me by adding +sign to the phonenumber like +1xxxxxxxxx instead clicking the button 'use my phonenumber' from the service db.  
Added more details to the bug .
